[package]
name = "btc-handshake"
version = "0.1.0"
edition = "2021"
authors = [
	"palutz, email@makeyourownbusiness.com",
]
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]

[dependencies]
num-traits = "0.2.17"
rand = "0.8.5"
sha2 = "0.10.8"
